### ISSUE TITLE
TypeError: getattr() takes no keyword arguments

### ISSUE THREAD

**Issue by edisonwine** [blueset/efb-wechat-slave#53] opened 2019-05-21 12:14 UTC
when I log in, the error will come
![15584408129936100462166194644845](https://user-images.githubusercontent.com/49673246/58095160-ee39f580-7c04-11e9-8370-73df1f2653df.jpg)

**Comment by blueset** [comment] 2019-05-26 11:06
Partial duplicate of #46.

**Comment by blueset** [comment] 2019-05-31 09:11
Fix released.

**Closed by blueset** 2019-05-31 09:11 UTC
Labels: bug
